name: Code Quality

on:
  pull_request: ~

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

      - name: Setup PHP
        uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2.37.2
        with:
          php-version: 8.1
          extensions: mongodb
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: Install Doctrine Mongodb ODM
        run: composer require doctrine/mongodb-odm --with-all-dependencies

      - name: Run PHPStan
        run: bin/phpstan

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

      - name: Setup PHP
        uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # v2.37.2
        with:
          php-version: 8.5
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: Run easy-coding-standard
        run: bin/ecs check
